name: CI setup for Go. #Name the workflow
on:  #on event keyword
  push:
    branches: [main]  #identifying branch
jobs: #Job to execute on event
  my-job:
    name: My Job
    runs-on: ubuntu-16.04 # specify OS in virtual machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! #run terminal command

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.14 #optional
    - name: show Go version
      run: go version

    - name: Checkout our codes
      uses: actions/checkout@v2
      
    - name: Check file system
      run: |
        ls
        cat calc.go #prints the content of calc.go
    
    - name: Checkout private repo remotely
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample #the hidden repo I am trying to access
        path: virtualRepoFolder #folder to save to in my virtual env
        token: ${{ secrets.GO_SECRET }}  #Pass to enter remote hidden repo
    
    - name: Show hidden files
      run: |
        cd virtualRepoFolder # to access the folder of interest in my virtual emv
        ls
        cat myText.txt # show content of file of interest
        cd ..
    - name: Install dependencies for GO
      run: |
        go get github.com/franela/goblin. #Adds package for Goblin testing
        go get github.com/tebeka/go2xunit :  #Adds package for conversion
        go test -v. #Command to run go test
